version: 2.1

jobs:
  build-clj:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-21.0
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Install static code analysis tools
          environment:
            CLJSTYLE_VERSION: 0.17.642
            CLJ_KONDO_VERSION: 2026.04.15
            JOKER_VERSION: 1.7.1
          command: |
            # cljstyle
            wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
            unzip -qq cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
            sudo mv -f cljstyle /usr/local/bin/
            # clj-kondo
            curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
            chmod +x install-clj-kondo
            sudo ./install-clj-kondo --version ${CLJ_KONDO_VERSION}
            # Joker
            wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-linux-amd64.zip
            unzip -qq joker-linux-amd64.zip
            sudo mv -f joker /usr/local/bin/
      - run: make lint-clj
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies-
      - run: make test-and-build-clj
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies--{{ checksum "deps.edn" }}

  build-scala:
    docker:
      - image: cimg/openjdk:25.0.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Install Coursier
          command: |
            # Coursier
            curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
            chmod +x cs
            ./cs setup --yes
            echo 'export PATH="$HOME/.local/share/coursier/bin:$PATH"' >> "$BASH_ENV"
      - run:
          name: Install static code analysis tools
          environment:
            SCALAFMT_VERSION: 3.11.0
            SCALAFIX_VERSION: 0.14.6
          command: |
            # Scalafmt
            cs install scalafmt:${SCALAFMT_VERSION}
            # Scalafix
            cs install scalafix:${SCALAFIX_VERSION}
      - run: make lint-scala
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: make compile-scala
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: make test-scala

  build-flix:
    docker:
      - image: cimg/openjdk:25.0.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Install Flix
          environment:
            FLIX_VERSION: 0.72.0
          command: |
            wget https://github.com/flix/flix/releases/download/v${FLIX_VERSION}/flix.jar
            echo 'exec java -jar ${CIRCLE_WORKING_DIRECTORY}/flix.jar' > flix
            chmod +x flix
            sudo mv -f flix /usr/local/bin/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "flix.toml" }}
            - v1-dependencies-
      - run: make lint-flix
      - run: make compile-flix
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "flix.toml" }}
      - run: make test-flix

workflows:
  builds:
    jobs:
      - build-clj
      - build-scala
      - build-flix
